---
version: 2

jobs:
  archive-create:
    working_directory: '/rpmbuild/hootenanny'
    docker:
      - image: hootenanny/rpmbuild-hoot-release@sha256:799f9bea926e15fe4a416c4c5c9f41a406ab8f9c7f1664ef56c6f5d8727ed172
    steps:
      - checkout
      - run:
          name: 'Git Submodules'
          command: |
            chown -R rpmbuild:rpmbuild .
            su-exec rpmbuild git submodule update --init --recursive
      - run:
          name: 'Make Hootenanny Archive'
          command: |
            su-exec postgres pg_ctl -D $PGDATA -s start
            su-exec rpmbuild bash -c "mkdir -p /rpmbuild/.m2 && curl -sSL https://hoot-maven.s3.amazonaws.com/m2-cache-2018-12-06.tar.gz | tar -C /rpmbuild/.m2 -xzf -"
            su-exec rpmbuild ./scripts/ci/archive.sh
            su-exec rpmbuild bash -c "mkdir -p archives && mv -v hootenanny-[0-9]*.tar.gz archives"
      - persist_to_workspace:
          root: archives
          paths:
            - hootenanny-*.tar.gz
  archive-upload:
    working_directory: '/rpmbuild/hootenanny'
    docker:
      - image: hootenanny/rpmbuild-repo@sha256:3188fdacecb7ae5659e0274828b66da4b000f37357ad6bd71478a82137c35eea
        user: rpmbuild
    steps:
      - attach_workspace:
          at: archives
      - run:
          name: 'Upload Hootenanny Archive'
          command: |
            find archives -type f -exec aws s3 cp {} s3://hoot-archives/circle/$CIRCLE_BRANCH/ \;
  copyright:
    working_directory: '/rpmbuild/hootenanny'
    docker:
      - image: hootenanny/rpmbuild-generic@sha256:15d3e188b3530c1dc8cb9c8b7ca67e97dfb1979796c8088966e63576550ed5c9
        user: rpmbuild
        environment:
          HOOT_HOME: '/rpmbuild/hootenanny'
    steps:
      - checkout
      - run:
          name: 'Check Copyright Headers'
          command: ./scripts/copyright/UpdateAllCopyrightHeaders.sh

workflows:
  version: 2
  tests:
    jobs:
      - archive-create
      - archive-upload:
          requires:
            - archive-create
      - copyright
