---
version: 2

jobs:
  archive-create:
    working_directory: '/rpmbuild/hootenanny'
    docker:
      - image: hootenanny/rpmbuild-hoot-release@sha256:1359c827664eb0b14fd8ff632ffe796b408cd3a57a49c08f4ea47db7f2260ccc
    steps:
      - checkout
      - run:
          name: 'Git Submodules'
          command: |
            chown -R rpmbuild:rpmbuild .
            su-exec rpmbuild git submodule update --init --recursive
      - run:
          name: 'Make Hootenanny Archive'
          command: |
            su-exec postgres pg_ctl -D $PGDATA -s start
            su-exec rpmbuild bash -c "mkdir -p /rpmbuild/.m2 && curl -sSL https://s3.amazonaws.com/hoot-maven/m2-cache-2018-10-02.tar.gz | tar -C /rpmbuild/.m2 -xzf -"
            su-exec rpmbuild ./scripts/ci/archive.sh
            su-exec rpmbuild bash -c "mkdir -p archives && mv -v hootenanny-[0-9]*.tar.gz archives"
      - persist_to_workspace:
          root: archives
          paths:
            - hootenanny-*.tar.gz
  archive-upload:
    working_directory: '/rpmbuild/hootenanny'
    docker:
      - image: hootenanny/rpmbuild-repo@sha256:a885b6c875ca3aaaf966c820728beeff8c13097b8ef9f288a2587d5a1d63c30b
        user: rpmbuild
    steps:
      - attach_workspace:
          at: archives
      - run:
          name: 'Upload Hootenanny Archive'
          command: |
            find archives -type f -exec aws s3 cp {} s3://hoot-archives/circle/$CIRCLE_BRANCH/ \;
  copyright:
    working_directory: '/rpmbuild/hootenanny'
    docker:
      - image: hootenanny/rpmbuild-generic@sha256:6378904ed09a847f2575111d32c13f36fb478405ce5b210db1fc43015275224f
        user: rpmbuild
        environment:
          HOOT_HOME: '/rpmbuild/hootenanny'
    steps:
      - checkout
      - run:
          name: 'Check Copyright Headers'
          command: ./scripts/copyright/UpdateAllCopyrightHeaders.sh

workflows:
  version: 2
  tests:
    jobs:
      - archive-create
      - archive-upload:
          requires:
            - archive-create
      - copyright
